CREATE TABLE address (
    address_id            NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    street               VARCHAR2(32 CHAR) NOT NULL,
    postal_code          VARCHAR2(32 CHAR) NOT NULL,
    city                 VARCHAR2(32 CHAR) NOT NULL,
    building_id NUMBER(4) NOT NULL
);

CREATE UNIQUE INDEX address__idx ON
    address (
        building_id
    ASC );

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( address_id );

CREATE TABLE building (
    building_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    name        VARCHAR2(32 CHAR) NOT NULL
);

ALTER TABLE building ADD CONSTRAINT building_pk PRIMARY KEY ( building_id );

CREATE TABLE classroom (
    classroom_id     NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    classroom_number NUMBER(3) NOT NULL,
    available        CHAR(1) NOT NULL,
    building_id      NUMBER(4) NOT NULL,
    number_of_seats  NUMBER(3) NOT NULL
);

ALTER TABLE classroom ADD CONSTRAINT classroom_pk PRIMARY KEY ( classroom_id );

CREATE TABLE course (
    course_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    name      VARCHAR2(32 CHAR) NOT NULL,
    ects      NUMBER(1) NOT NULL
);

ALTER TABLE course ADD CONSTRAINT course_pk PRIMARY KEY ( course_id );

CREATE TABLE course_employee (
    employee_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    course_id   NUMBER(4) NOT NULL
);

ALTER TABLE course_employee ADD CONSTRAINT relation_3_pk PRIMARY KEY ( employee_id,
                                                                       course_id );

CREATE TABLE employee (
    employee_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    name        VARCHAR2(32 CHAR) NOT NULL,
    surname     VARCHAR2(32 CHAR) NOT NULL
);

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );

CREATE TABLE major (
    major_id    NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    name        VARCHAR2(32 CHAR) NOT NULL,
    semester    NUMBER(4) NOT NULL
);

ALTER TABLE major ADD CONSTRAINT major_pk PRIMARY KEY ( major_id );

CREATE TABLE reservation (
    reservation_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    res_start      DATE NOT NULL,
    res_end        DATE NOT NULL,
    employee_id    NUMBER(4),
    course_id      NUMBER(4),
    classroom_id   NUMBER(4)
);

ALTER TABLE reservation ADD CONSTRAINT reservation_pk PRIMARY KEY ( reservation_id );

CREATE TABLE student (
    student_id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    name       VARCHAR2(32 CHAR) NOT NULL,
    surname    VARCHAR2(32) NOT NULL,
    major_id   NUMBER(4) NOT NULL,
    ects_total NUMBER(4) NOT NULL
);

ALTER TABLE student ADD CONSTRAINT student_pk PRIMARY KEY ( student_id );

CREATE TABLE student_course (
    student_id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 NOT NULL,
    course_id  NUMBER(4) NOT NULL
);

ALTER TABLE student_course ADD CONSTRAINT relation_2_pk PRIMARY KEY ( student_id,
                                                                      course_id );

ALTER TABLE address
    ADD CONSTRAINT address_building_fk FOREIGN KEY ( building_id )
        REFERENCES building ( building_id );

ALTER TABLE classroom
    ADD CONSTRAINT classroom_building_fk FOREIGN KEY ( building_id )
        REFERENCES building ( building_id );

ALTER TABLE student_course
    ADD CONSTRAINT relation_2_course_fk FOREIGN KEY ( course_id )
        REFERENCES course ( course_id );

ALTER TABLE student_course
    ADD CONSTRAINT relation_2_student_fk FOREIGN KEY ( student_id )
        REFERENCES student ( student_id );

ALTER TABLE course_employee
    ADD CONSTRAINT relation_3_course_fk FOREIGN KEY ( course_id )
        REFERENCES course ( course_id );

ALTER TABLE course_employee
    ADD CONSTRAINT relation_3_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_classroom_fk FOREIGN KEY ( classroom_id )
        REFERENCES classroom ( classroom_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_course_fk FOREIGN KEY ( course_id )
        REFERENCES course ( course_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE student
    ADD CONSTRAINT student_major_fk FOREIGN KEY ( major_id )
        REFERENCES major ( major_id );
